// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALH0dIjsmmD0qG8elr3ctfDQWidcGbopk',
    appId: '1:369280597019:web:2b4d29e13e3c793932ccbe',
    messagingSenderId: '369280597019',
    projectId: 'masarak-gwy',
    authDomain: 'masarak-gwy.firebaseapp.com',
    storageBucket: 'masarak-gwy.firebasestorage.app',
    measurementId: 'G-EXXR5TDXHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEWdo0WfmA3aLJrUbCI9I0YGgrGDh6RfQ',
    appId: '1:369280597019:android:2ea3139788331e7032ccbe',
    messagingSenderId: '369280597019',
    projectId: 'masarak-gwy',
    storageBucket: 'masarak-gwy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAentEIrz6J3m6ci_-VAJV8WY4ShZKfqSs',
    appId: '1:369280597019:ios:71eb4ec6dc8e830b32ccbe',
    messagingSenderId: '369280597019',
    projectId: 'masarak-gwy',
    storageBucket: 'masarak-gwy.firebasestorage.app',
    iosBundleId: 'iq.gwy.masarak.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAentEIrz6J3m6ci_-VAJV8WY4ShZKfqSs',
    appId: '1:369280597019:ios:dc4346e9178be79c32ccbe',
    messagingSenderId: '369280597019',
    projectId: 'masarak-gwy',
    storageBucket: 'masarak-gwy.firebasestorage.app',
    iosBundleId: 'iq.gwy.masarakDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALH0dIjsmmD0qG8elr3ctfDQWidcGbopk',
    appId: '1:369280597019:web:2a3c17c01b46c60d32ccbe',
    messagingSenderId: '369280597019',
    projectId: 'masarak-gwy',
    authDomain: 'masarak-gwy.firebaseapp.com',
    storageBucket: 'masarak-gwy.firebasestorage.app',
    measurementId: 'G-GTCTLGVFXH',
  );

}