import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:masarak/pages/trip/models/trip_info_res/trip_info_res.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'trip_info_state.freezed.dart';

@freezed
sealed class TripInfoState with _$TripInfoState {
  const factory TripInfoState.initial() = TripInfoStateInitial;
  const factory TripInfoState.loading() = TripInfoStateLoading;

  const factory TripInfoState.loaded({
    required String message,
    required TripInfoRes res,
  }) = TripInfoStateLoaded;
  const factory TripInfoState.error({
    required String message,
    StackTrace? stackTrace,
  }) = TripInfoStateError;
}
