import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'check_point.freezed.dart';
// optional: Since our CheckPoint class is serializable, we must add this line.
// But if CheckPoint was not serializable, we could skip it.
part 'check_point.g.dart';

@freezed
abstract class CheckPoint with _$CheckPoint {
  const factory CheckPoint({
    @JsonKey(name: 'check_point_name') String? checkPointname,
    // required int age,
  }) = _CheckPoint;

  factory CheckPoint.fromJson(Map<String, Object?> json) =>
      _$CheckPointFromJson(json);
}
