// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'trip.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_Trip _$TripFromJson(Map<String, dynamic> json) => _Trip(
  name: json['name'] as String?,
  creation: json['creation'] as String?,
  modified: json['modified'] as String?,
  modifiedBy: json['modified_by'] as String?,
  owner: json['owner'] as String?,
  docstatus: (json['docstatus'] as num?)?.toInt(),
  idx: (json['idx'] as num?)?.toInt(),
  userTags: json['_user_tags'],
  comments: json['_comments'],
  assign: json['_assign'],
  likedBy: json['_liked_by'],
  containerNumber: json['container_number'],
  jobOrder: json['job_order'],
  jobRequest: json['job_request'] as String?,
  queue: json['queue'],
  weight: (json['weight'] as num?)?.toInt(),
  truck: json['truck'] as String?,
  tripCode: json['trip_code'],
  workflowState: json['workflow_state'] as String?,
  driver: json['driver'] as String?,
  driverName: json['driver_name'] as String?,
  driverMotherName: json['driver_mother_name'] as String?,
  truckNumber: json['truck_number'] as String?,
  cargoType: json['cargo_type'] as String?,
  portName: json['port_name'] as String?,
  berthName: json['berth_name'] as String?,
  currentCheckPoint: json['current_check_point'],
  currentProcedure: json['current_procedure'],
  exitFromMiddleCustom: json['exit_from_middle_custom'] as String?,
  containerNumberExport: json['container_number_export'],
  containerNumberReturn: json['container_number_return'],
  berth: json['berth'] as String?,
  secondContainerNumberReturn: json['second_container_number_return'],
  seen: json['_seen'] as String?,
  returnContainerSize: json['return_container_size'] as String?,
  transportationAgent: json['transportation_agent'] as String?,
  amendedFrom: json['amended_from'],
  isReturnOnly: (json['is_return_only'] as num?)?.toInt(),
  namingSeries: json['naming_series'] as String?,
  isRefeer: (json['is_refeer'] as num?)?.toInt(),
  tripUuid: json['trip_uuid'] as String?,
  uniqueIdentifierCustomsNumber:
      json['unique_identifier_customs_number'] as String?,
  truckCity: json['truck_city'] as String?,
  containerSize: json['container_size'] as String?,
  legalMainQueue: (json['legal_main_queue'] as num?)?.toInt(),
  legalYardQueue: (json['legal_yard_queue'] as num?)?.toInt(),
  returnJobRequest: json['return_job_request'],
  returnJobRequestSecond: json['return_job_request_second'],
  returnBerthName: json['return_berth_name'],
  linkedTransportationAgent: json['linked_transportation_agent'],
  linkedBaseType: json['linked_base_type'],
  transactional: json['transactional'] as String?,
  paid: (json['paid'] as num?)?.toInt(),
  customTruckNumber: json['custom_truck_number'],
  onlyReturnTrip: (json['only_return_trip'] as num?)?.toInt(),
  excludeFromImport: (json['exclude_from_import'] as num?)?.toInt(),
  globalQueueNumber: json['global_queue_number'],
  berthQueueNumber: json['berth_queue_number'],
  secondContainerNumber: json['second_container_number'],
  secondContainer: json['second_container'],
  printingAgent: const PrintingAgentSerializer().fromJson(
    json['printing_agent'],
  ),
  truckTagId: json['truck_tag_id'],
  weight1: json['weight1'],
  weight2: json['weight2'],
);

Map<String, dynamic> _$TripToJson(_Trip instance) => <String, dynamic>{
  'name': instance.name,
  'creation': instance.creation,
  'modified': instance.modified,
  'modified_by': instance.modifiedBy,
  'owner': instance.owner,
  'docstatus': instance.docstatus,
  'idx': instance.idx,
  '_user_tags': instance.userTags,
  '_comments': instance.comments,
  '_assign': instance.assign,
  '_liked_by': instance.likedBy,
  'container_number': instance.containerNumber,
  'job_order': instance.jobOrder,
  'job_request': instance.jobRequest,
  'queue': instance.queue,
  'weight': instance.weight,
  'truck': instance.truck,
  'trip_code': instance.tripCode,
  'workflow_state': instance.workflowState,
  'driver': instance.driver,
  'driver_name': instance.driverName,
  'driver_mother_name': instance.driverMotherName,
  'truck_number': instance.truckNumber,
  'cargo_type': instance.cargoType,
  'port_name': instance.portName,
  'berth_name': instance.berthName,
  'current_check_point': instance.currentCheckPoint,
  'current_procedure': instance.currentProcedure,
  'exit_from_middle_custom': instance.exitFromMiddleCustom,
  'container_number_export': instance.containerNumberExport,
  'container_number_return': instance.containerNumberReturn,
  'berth': instance.berth,
  'second_container_number_return': instance.secondContainerNumberReturn,
  '_seen': instance.seen,
  'return_container_size': instance.returnContainerSize,
  'transportation_agent': instance.transportationAgent,
  'amended_from': instance.amendedFrom,
  'is_return_only': instance.isReturnOnly,
  'naming_series': instance.namingSeries,
  'is_refeer': instance.isRefeer,
  'trip_uuid': instance.tripUuid,
  'unique_identifier_customs_number': instance.uniqueIdentifierCustomsNumber,
  'truck_city': instance.truckCity,
  'container_size': instance.containerSize,
  'legal_main_queue': instance.legalMainQueue,
  'legal_yard_queue': instance.legalYardQueue,
  'return_job_request': instance.returnJobRequest,
  'return_job_request_second': instance.returnJobRequestSecond,
  'return_berth_name': instance.returnBerthName,
  'linked_transportation_agent': instance.linkedTransportationAgent,
  'linked_base_type': instance.linkedBaseType,
  'transactional': instance.transactional,
  'paid': instance.paid,
  'custom_truck_number': instance.customTruckNumber,
  'only_return_trip': instance.onlyReturnTrip,
  'exclude_from_import': instance.excludeFromImport,
  'global_queue_number': instance.globalQueueNumber,
  'berth_queue_number': instance.berthQueueNumber,
  'second_container_number': instance.secondContainerNumber,
  'second_container': instance.secondContainer,
  'printing_agent': const PrintingAgentSerializer().toJson(
    instance.printingAgent,
  ),
  'truck_tag_id': instance.truckTagId,
  'weight1': instance.weight1,
  'weight2': instance.weight2,
};
