import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:masarak/pages/home/models/check_point.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'check_point_model.freezed.dart';
// optional: Since our CheckPointState class is serializable, we must add this line.
// But if CheckPointState was not serializable, we could skip it.
part 'check_point_model.g.dart';

@freezed
class CheckPointState with _$CheckPointState {
  const factory CheckPointState({
    String? errorMessage,
    int? statusCode,
    @Default(false) bool isLoading,
    @Default([]) List<CheckPoint> checkPoints,
    // required int age,
  }) = _CheckPointState;

  factory CheckPointState.fromJson(Map<String, Object?> json) =>
      _$CheckPointStateFromJson(json);
}
