import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'validate_user_state.freezed.dart';
// optional: Since our ValidateUser class is serializable, we must add this line.
// But if ValidateUser was not serializable, we could skip it.
part 'validate_user_state.g.dart';

@freezed
class ValidateUser with _$ValidateUser {
  const factory ValidateUser({
    String? errorMessage,
    @Default(false) bool isLoading,
    // required int age,
  }) = _ValidateUser;

  factory ValidateUser.fromJson(Map<String, Object?> json) =>
      _$ValidateUserFromJson(json);
}
